import type { StockCall } from "./types";

const series = (seed: number, len = 40, drift = 0.6) => {
  let v = 100;
  let s = seed;
  const out: number[] = [];
  for (let i = 0; i < len; i++) {
    s = (s * 9301 + 49297) % 233280;
    const r = s / 233280 - 0.5;
    v = v + r * 4 + drift;
    out.push(Number(v.toFixed(2)));
  }
  return out;
};

export const mockCalls: StockCall[] = [
  {
    id: "ml-100",
    stock: "Rossell Techsys Limited",
    ticker: "ROSSTECH",
    exchange: "NSE / BSE",
    sector: "Aerospace & Defence",
    direction: "long",
    callNumber: 1,
    status: "live",
    access: "paid",
    price: 499,
    currentPrice: 1090.2,
    changePct: 2.4,
    entry: 1080,
    target: 1200,
    stopLoss: 999,
    term: "Short Term",
    coverage: "Weekly Pick",
    segment: "Cash / Equity",
    timeframe: "15 - 20 Trading Days",
    publishedAt: "2026-08-09",
    summary:
      "Fresh breakout above the 1,080-1,090 supply zone that capped price through May-August.",
    view:
      "Rossell Techsys has broken out to a fresh high of Rs 1,090.2 (+2.40%), reclaiming the 1,080-1,090 supply zone that had capped price action through May-August. A sustained move above this zone on rising volume would open the path toward the Rs 1,200+ target over the next 15-20 trading sessions. A close back below Rs 999 would invalidate this setup and should be treated as the risk-control exit.",
    catalysts: ["Supply zone reclaim", "Volume expansion", "Aero order pipeline"],
    confidence: 78,
    series: series(23, 40, 1.0),
    research: [
      {
        heading: "Structure",
        body: "Three failed attempts at 1,090 between May and August built the supply shelf. The fourth attempt cleared it on above-average volume, which flips that shelf into demand.",
      },
      {
        heading: "Execution plan",
        body: "Enter on strength near Rs 1,080 and add only above the breakout candle high. Book partial at Rs 1,200 and trail the balance.",
      },
      {
        heading: "Risk control",
        body: "A daily close below Rs 999 negates the breakout. Position size so that the full stop costs no more than 1% of capital.",
      },
    ],
  },
  {
    id: "ml-101",
    stock: "Tata Elxsi",
    ticker: "TATAELXSI",
    exchange: "NSE",
    sector: "IT Services",
    direction: "long",
    callNumber: 2,
    status: "live",
    access: "paid",
    price: 499,
    currentPrice: 6412.5,
    changePct: 1.42,
    entry: 6280,
    target: 7450,
    stopLoss: 5940,
    term: "Positional",
    coverage: "Weekly Pick",
    segment: "Cash / Equity",
    timeframe: "30 - 45 Trading Days",
    publishedAt: "2026-08-07",
    summary:
      "Design-led engineering franchise turning the corner as auto software deals re-accelerate after four muted quarters.",
    view:
      "Tata Elxsi is trading at Rs 6412.5 and is being tracked against an entry band around Rs 6280. A sustained move on rising volume opens the path toward the Rs 7450 target over the next 30 - 45 trading days. A close below Rs 5940 invalidates the setup and should be treated as the risk-control exit.",
    catalysts: ["Order book re-rating", "EV software mandates", "Margin recovery"],
    confidence: 82,
    series: series(11, 40, 0.9),
    research: [
      {
        heading: "Why now",
        body: "Deal wins in automotive software have compounded for two consecutive quarters while the street still models a flat FY. The gap between reported order intake and consensus revenue is the mispricing we are underwriting.",
      },
      {
        heading: "Valuation",
        body: "Trading at 46x forward earnings versus a five-year median of 58x. Even a partial reversion with 14% earnings growth supports our target.",
      },
      {
        heading: "Risk",
        body: "A delay in European auto capex would push the thesis out by two quarters. We exit below the stop rather than average down.",
      },
    ],
  },
  {
    id: "ml-102",
    stock: "Bharat Electronics",
    ticker: "BEL",
    exchange: "NSE",
    sector: "Defence",
    direction: "long",
    callNumber: 3,
    status: "live",
    access: "paid",
    price: 599,
    currentPrice: 388.2,
    changePct: 2.4,
    entry: 372,
    target: 452,
    stopLoss: 344,
    term: "Swing",
    coverage: "Weekly Pick",
    segment: "Cash / Equity",
    timeframe: "15 - 20 Trading Days",
    publishedAt: "2026-08-06",
    summary:
      "Record executable order book with a defence budget cycle that has not yet been priced into FY28 estimates.",
    view:
      "Bharat Electronics is trading at Rs 388.2 and is being tracked against an entry band around Rs 372. A sustained move on rising volume opens the path toward the Rs 452 target over the next 15 - 20 trading days. A close below Rs 344 invalidates the setup and should be treated as the risk-control exit.",
    catalysts: ["Order inflow guidance", "Export approvals", "Margin beat"],
    confidence: 76,
    series: series(29, 40, 0.7),
    research: [
      {
        heading: "Thesis",
        body: "Execution visibility now extends beyond three years. Historically the stock re-rates when the book-to-bill crosses 3.5x, which happened last quarter.",
      },
      {
        heading: "Positioning",
        body: "Accumulate in two tranches — the first at entry, the second only on a close above the prior swing high.",
      },
    ],
  },
  {
    id: "ml-201",
    stock: "Cummins India",
    ticker: "CUMMINSIND",
    exchange: "NSE",
    sector: "Industrials",
    direction: "long",
    callNumber: 1,
    status: "closed",
    access: "free",
    price: 0,
    currentPrice: 4210,
    changePct: 0.42,
    entry: 3480,
    target: 4180,
    stopLoss: 3240,
    exitPrice: 4180,
    term: "Positional",
    coverage: "Conviction Pick",
    segment: "Cash / Equity",
    timeframe: "45 - 60 Trading Days",
    publishedAt: "2026-05-12",
    closedAt: "2026-07-29",
    summary:
      "Data-centre powergen demand plus export recovery drove a full target hit in eleven weeks.",
    view:
      "Cummins India is trading at Rs 4210 and is being tracked against an entry band around Rs 3480. A sustained move on rising volume opens the path toward the Rs 4180 target over the next 45 - 60 trading days. A close below Rs 3240 invalidates the setup and should be treated as the risk-control exit.",
    catalysts: ["Powergen demand", "Export recovery"],
    confidence: 84,
    series: series(19, 44, 1.4),
    research: [
      {
        heading: "How it played out",
        body: "The export order commentary in the June quarter was the trigger. Price gapped through resistance and never revisited the entry band.",
      },
      {
        heading: "Lesson",
        body: "Sizing up on the confirmation candle rather than the base would have improved realised return without changing risk.",
      },
    ],
  },
  {
    id: "ml-202",
    stock: "Info Edge",
    ticker: "NAUKRI",
    exchange: "NSE",
    sector: "Internet",
    direction: "long",
    callNumber: 2,
    status: "closed",
    access: "free",
    price: 0,
    currentPrice: 1385,
    changePct: -0.31,
    entry: 1460,
    target: 1720,
    stopLoss: 1372,
    exitPrice: 1372,
    term: "Swing",
    coverage: "Weekly Pick",
    segment: "Cash / Equity",
    timeframe: "15 - 20 Trading Days",
    publishedAt: "2026-04-02",
    closedAt: "2026-05-06",
    summary:
      "Billings growth decelerated faster than modelled. Stopped out mechanically, no discretion.",
    view:
      "Info Edge is trading at Rs 1385 and is being tracked against an entry band around Rs 1460. A sustained move on rising volume opens the path toward the Rs 1720 target over the next 15 - 20 trading days. A close below Rs 1372 invalidates the setup and should be treated as the risk-control exit.",
    catalysts: ["Billings growth"],
    confidence: 58,
    series: series(97, 44, -0.9),
    research: [
      {
        heading: "Post-mortem",
        body: "We underwrote a recruitment recovery that had not yet shown up in billings. The stop did its job — the position closed at a defined loss instead of a compounding one.",
      },
    ],
  },
  {
    id: "ml-203",
    stock: "Aurobindo Pharma",
    ticker: "AUROPHARMA",
    exchange: "NSE",
    sector: "Pharma",
    direction: "long",
    callNumber: 3,
    status: "closed",
    access: "free",
    price: 0,
    currentPrice: 1490,
    changePct: 1.06,
    entry: 1188,
    target: 1420,
    stopLoss: 1090,
    exitPrice: 1447,
    term: "Positional",
    coverage: "Conviction Pick",
    segment: "Cash / Equity",
    timeframe: "45 - 60 Trading Days",
    publishedAt: "2026-03-18",
    closedAt: "2026-06-24",
    summary: "US injectables approvals landed early; exited above target on strength.",
    view:
      "Aurobindo Pharma is trading at Rs 1490 and is being tracked against an entry band around Rs 1188. A sustained move on rising volume opens the path toward the Rs 1420 target over the next 45 - 60 trading days. A close below Rs 1090 invalidates the setup and should be treated as the risk-control exit.",
    catalysts: ["ANDA approvals", "Injectables ramp"],
    confidence: 80,
    series: series(53, 44, 1.2),
    research: [
      {
        heading: "Execution",
        body: "Two approvals inside a single month reset the FY revenue base. We trailed the stop and exited on the first distribution day.",
      },
    ],
  },
  {
    id: "ml-204",
    stock: "IndusInd Bank",
    ticker: "INDUSINDBK",
    exchange: "NSE",
    sector: "Banking",
    direction: "long",
    callNumber: 1,
    status: "closed",
    access: "free",
    price: 0,
    currentPrice: 1042,
    changePct: 0.58,
    entry: 962,
    target: 1145,
    stopLoss: 905,
    exitPrice: 1058,
    term: "Swing",
    coverage: "Weekly Pick",
    segment: "Cash / Equity",
    timeframe: "15 - 25 Trading Days",
    publishedAt: "2026-02-11",
    closedAt: "2026-04-08",
    summary: "Partial exit at 10% as asset-quality commentary turned mixed.",
    view:
      "IndusInd Bank is trading at Rs 1042 and is being tracked against an entry band around Rs 962. A sustained move on rising volume opens the path toward the Rs 1145 target over the next 15 - 25 trading days. A close below Rs 905 invalidates the setup and should be treated as the risk-control exit.",
    catalysts: ["NIM stability"],
    confidence: 66,
    series: series(71, 44, 0.6),
    research: [
      {
        heading: "Why we closed early",
        body: "Slippage guidance widened. When the reason for owning changes, the position closes regardless of the target.",
      },
    ],
  },
  {
    id: "ml-205",
    stock: "Astral",
    ticker: "ASTRAL",
    exchange: "NSE",
    sector: "Building Materials",
    direction: "long",
    callNumber: 2,
    status: "archived",
    access: "free",
    price: 0,
    currentPrice: 1620,
    changePct: 0.22,
    entry: 1512,
    target: 1780,
    stopLoss: 1430,
    exitPrice: 1698,
    term: "Long Term",
    coverage: "Conviction Pick",
    segment: "Cash / Equity",
    timeframe: "60 - 90 Trading Days",
    publishedAt: "2025-11-20",
    closedAt: "2026-02-02",
    summary: "Volume-led recovery in pipes played out over a full quarter.",
    view:
      "Astral is trading at Rs 1620 and is being tracked against an entry band around Rs 1512. A sustained move on rising volume opens the path toward the Rs 1780 target over the next 60 - 90 trading days. A close below Rs 1430 invalidates the setup and should be treated as the risk-control exit.",
    catalysts: ["Volume growth", "PVC price stability"],
    confidence: 73,
    series: series(37, 44, 0.8),
    research: [
      {
        heading: "Archive note",
        body: "Retained in the archive as a reference case for how PVC price stability translates into distributor restocking.",
      },
    ],
  },
];
