/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClosedRouteImport } from './routes/closed'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminResearchRouteImport } from './routes/admin.research'
import { Route as AdminWatchlistRouteImport } from './routes/admin.watchlist'
import { Route as CallCallIdRouteImport } from './routes/call.$callId'
import { Route as CheckoutCallIdRouteImport } from './routes/checkout.$callId'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as AdminEditorCallIdRouteImport } from './routes/admin.editor.$callId'
import { Route as ApiPublicWebhooksRazorpayRouteImport } from './routes/api/public/webhooks/razorpay'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClosedRoute = ClosedRouteImport.update({
  id: '/closed',
  path: '/closed',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResearchRoute = AdminResearchRouteImport.update({
  id: '/admin/research',
  path: '/admin/research',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWatchlistRoute = AdminWatchlistRouteImport.update({
  id: '/admin/watchlist',
  path: '/admin/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const CallCallIdRoute = CallCallIdRouteImport.update({
  id: '/call/$callId',
  path: '/call/$callId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCallIdRoute = CheckoutCallIdRouteImport.update({
  id: '/checkout/$callId',
  path: '/checkout/$callId',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/insights/$slug',
  path: '/insights/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEditorCallIdRoute = AdminEditorCallIdRouteImport.update({
  id: '/admin/editor/$callId',
  path: '/admin/editor/$callId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksRazorpayRoute =
  ApiPublicWebhooksRazorpayRouteImport.update({
    id: '/api/public/webhooks/razorpay',
    path: '/api/public/webhooks/razorpay',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/closed': typeof ClosedRoute
  '/research': typeof ResearchRoute
  '/admin/research': typeof AdminResearchRoute
  '/admin/watchlist': typeof AdminWatchlistRoute
  '/call/$callId': typeof CallCallIdRoute
  '/checkout/$callId': typeof CheckoutCallIdRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/admin/editor/$callId': typeof AdminEditorCallIdRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/closed': typeof ClosedRoute
  '/research': typeof ResearchRoute
  '/admin/research': typeof AdminResearchRoute
  '/admin/watchlist': typeof AdminWatchlistRoute
  '/call/$callId': typeof CallCallIdRoute
  '/checkout/$callId': typeof CheckoutCallIdRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/admin/editor/$callId': typeof AdminEditorCallIdRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/closed': typeof ClosedRoute
  '/research': typeof ResearchRoute
  '/admin/research': typeof AdminResearchRoute
  '/admin/watchlist': typeof AdminWatchlistRoute
  '/call/$callId': typeof CallCallIdRoute
  '/checkout/$callId': typeof CheckoutCallIdRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/admin/editor/$callId': typeof AdminEditorCallIdRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/closed'
    | '/research'
    | '/admin/research'
    | '/admin/watchlist'
    | '/call/$callId'
    | '/checkout/$callId'
    | '/insights/$slug'
    | '/admin/'
    | '/insights/'
    | '/admin/editor/$callId'
    | '/api/public/webhooks/razorpay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/closed'
    | '/research'
    | '/admin/research'
    | '/admin/watchlist'
    | '/call/$callId'
    | '/checkout/$callId'
    | '/insights/$slug'
    | '/admin'
    | '/insights'
    | '/admin/editor/$callId'
    | '/api/public/webhooks/razorpay'
  id:
    | '__root__'
    | '/'
    | '/closed'
    | '/research'
    | '/admin/research'
    | '/admin/watchlist'
    | '/call/$callId'
    | '/checkout/$callId'
    | '/insights/$slug'
    | '/admin/'
    | '/insights/'
    | '/admin/editor/$callId'
    | '/api/public/webhooks/razorpay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClosedRoute: typeof ClosedRoute
  ResearchRoute: typeof ResearchRoute
  AdminResearchRoute: typeof AdminResearchRoute
  AdminWatchlistRoute: typeof AdminWatchlistRoute
  CallCallIdRoute: typeof CallCallIdRoute
  CheckoutCallIdRoute: typeof CheckoutCallIdRoute
  InsightsSlugRoute: typeof InsightsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  AdminEditorCallIdRoute: typeof AdminEditorCallIdRoute
  ApiPublicWebhooksRazorpayRoute: typeof ApiPublicWebhooksRazorpayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/closed': {
      id: '/closed'
      path: '/closed'
      fullPath: '/closed'
      preLoaderRoute: typeof ClosedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/research': {
      id: '/admin/research'
      path: '/admin/research'
      fullPath: '/admin/research'
      preLoaderRoute: typeof AdminResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/watchlist': {
      id: '/admin/watchlist'
      path: '/admin/watchlist'
      fullPath: '/admin/watchlist'
      preLoaderRoute: typeof AdminWatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call/$callId': {
      id: '/call/$callId'
      path: '/call/$callId'
      fullPath: '/call/$callId'
      preLoaderRoute: typeof CallCallIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$callId': {
      id: '/checkout/$callId'
      path: '/checkout/$callId'
      fullPath: '/checkout/$callId'
      preLoaderRoute: typeof CheckoutCallIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/insights/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/editor/$callId': {
      id: '/admin/editor/$callId'
      path: '/admin/editor/$callId'
      fullPath: '/admin/editor/$callId'
      preLoaderRoute: typeof AdminEditorCallIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/razorpay': {
      id: '/api/public/webhooks/razorpay'
      path: '/api/public/webhooks/razorpay'
      fullPath: '/api/public/webhooks/razorpay'
      preLoaderRoute: typeof ApiPublicWebhooksRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClosedRoute: ClosedRoute,
  ResearchRoute: ResearchRoute,
  AdminResearchRoute: AdminResearchRoute,
  AdminWatchlistRoute: AdminWatchlistRoute,
  CallCallIdRoute: CallCallIdRoute,
  CheckoutCallIdRoute: CheckoutCallIdRoute,
  InsightsSlugRoute: InsightsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  AdminEditorCallIdRoute: AdminEditorCallIdRoute,
  ApiPublicWebhooksRazorpayRoute: ApiPublicWebhooksRazorpayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
